# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'

- bash: 'ls -la'
  workingDirectory: ''
  displayName: 'List files'

- bash: 'ls -la src/test/python'
  workingDirectory: ''
  displayName: 'List test python files'

- bash: 'python src/test/python/example_test.py'
  workingDirectory: ''
  displayName: 'Run Example Python'

    